config/routes.rb
Rails.application.routes.draw do
  resources :moos

  devise_for :users
  get 'pages/home'
  get 'about' => 'pages#about'

  
  root 'pages#home'

end

app/models/moo.rb
class Moo < ActiveRecord::Base
  validates :context, presence: true
  
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :moos, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/moos_controller.rb
class MoosController < ApplicationController
  before_action :set_moo, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  
  respond_to :html

  def index
    @moos = Moo.order('updated_at DESC')
    respond_with(@moos)
  end

  def show
    respond_with(@moo)
  end

  def new
    @moo = Moo.new
    respond_with(@moo)
  end

  def edit
  end

  def create
    @moo = Moo.new(moo_params)
    @moo.user_id = current_user.id
    @moo.save
    respond_with(@moo)
  end

  def update
    @moo.update(moo_params)
    respond_with(@moo)
  end

  def destroy
    @moo.destroy
    respond_with(@moo)
  end

  private
    def set_moo
      @moo = Moo.find(params[:id])
    end

    def moo_params
      params.require(:moo).permit(:context)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/moos_helper.rb
module MoosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="/"><i class="fa fa-bullhorn"></i>Bullhorn</a> -->
      
      <% if current_user%>
        <%= link_to "<i class='fa fa-bullhorn'></i> View Moos".html_safe, moos_path, class: "navbar-brand" %>
      <% else %>
        <%= link_to "<i class='fa fa-bullhorn'></i> Bullhorn".html_safe, root_path, class: "navbar-brand" %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
          <% if current_user%>
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
              <li><%= link_to "About", about_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <title>Bullhorn</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header"%> 
<div class = "container">
  <%= yield %>
</div>

</body>
</html>

app/views/moos/_form.html.erb
<%= simple_form_for(@moo) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :context, label: "Content" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/moos/edit.html.erb
<h1>Editing moo</h1>

<%= render 'form' %>

<%= link_to 'Show', @moo %> |
<%= link_to 'Back', moos_path %>

app/views/moos/index.html.erb
<h1>Recent moos</h1>

<% @moos.each do |moo| %>
<div class="panel panel-default">
  <div class="panel-body">
    <%= moo.context %>
  </div>
  <div class="panel-footer"> sent by <b> <%= moo.user.email %> </b> on <%= moo.created_at.strftime("%b %d, %Y %T") %></div>
</div>

<% end %>
<br>

<%= link_to 'New Moo', new_moo_path %>

app/views/moos/new.html.erb
<h1>New moo</h1>

<%= render 'form' %>

<%= link_to 'Back', moos_path %>

app/views/moos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @moo.context %>
</p>

<%= link_to 'Edit', edit_moo_path(@moo) %> |
<%= link_to 'Back', moos_path %>

app/views/pages/about.html.erb
<h1>About me</h1>
<p>My name is Ricardo Kreyhsig and I'm learning Rails by building this twitter like app.  Enjoy!</p>
<p>You can reach me at rickreyhsig at gmail dot com</p>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1> <i class="fa fa-bullhorn"></i>Bullhorn</h1>
  <p>This is my twitter clone application</p>
    <% if current_user%>
      <%= link_to "Send a Moo", new_moo_path, class: "btn btn-primary btn-lg" %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
    <% end %>
  
</div>